# Generated by Django 5.2.7 on 2025-10-22 04:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangay',
            options={'ordering': ['province', 'municipality', 'name'], 'verbose_name_plural': 'Barangays'},
        ),
        migrations.AddField(
            model_name='barangay',
            name='children_population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barangay',
            name='elderly_population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='poverty_incidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='psgc_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='region',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barangay',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ResilienceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_exposure_score', models.FloatField(default=0)),
                ('health_sensitivity_score', models.FloatField(default=0)),
                ('adaptive_capacity_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('risk_level', models.CharField(default='Unknown', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resilience', to='resilience.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='HazardExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(choices=[('flood', 'Flood'), ('cyclone', 'Tropical Cyclone'), ('landslide', 'Landslide'), ('storm_surge', 'Storm Surge')], max_length=50)),
                ('susceptibility', models.CharField(max_length=50)),
                ('susceptibility_score', models.IntegerField()),
                ('source', models.CharField(default='LDRRMD', max_length=200)),
                ('assessed_date', models.DateField(blank=True, null=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='resilience.barangay')),
            ],
            options={
                'unique_together': {('barangay', 'hazard_type')},
            },
        ),
    ]
