# Generated by Django 5.2.7 on 2025-10-22 04:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience', '0002_alter_barangay_options_barangay_children_population_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psgc_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('classification', models.CharField(default='Municipality', max_length=50)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('land_area', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
                'ordering': ['province', 'name'],
            },
        ),
        migrations.AddField(
            model_name='barangay',
            name='municipality_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barangays', to='resilience.municipality'),
        ),
    ]
