# Generated by Django 5.2.7 on 2025-10-24 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience', '0004_alter_resiliencescore_options_barangay_adm4_pcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangayhealthaccess',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='barangayinfrastructure',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='diseasecase',
            name='barangay',
        ),
        migrations.RenameField(
            model_name='resiliencescore',
            old_name='climate_stress_score',
            new_name='population_density_score',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='adm4_pcode',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='building_density',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='built_up_area_pct',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='distance_to_coast',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='nightlight_mean',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='wealth_index_mean',
        ),
        migrations.RemoveField(
            model_name='resiliencescore',
            name='health_vulnerability_score',
        ),
        migrations.RemoveField(
            model_name='resiliencescore',
            name='healthcare_access_score',
        ),
        migrations.RemoveField(
            model_name='resiliencescore',
            name='infrastructure_score',
        ),
        migrations.CreateModel(
            name='NOAHFloodHazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flood_5yr_low_pct', models.FloatField(blank=True, help_text='% of area in low flood zone', null=True)),
                ('flood_5yr_med_pct', models.FloatField(blank=True, null=True)),
                ('flood_5yr_high_pct', models.FloatField(blank=True, null=True)),
                ('flood_25yr_low_pct', models.FloatField(blank=True, null=True)),
                ('flood_25yr_med_pct', models.FloatField(blank=True, null=True)),
                ('flood_25yr_high_pct', models.FloatField(blank=True, null=True)),
                ('flood_100yr_low_pct', models.FloatField(blank=True, null=True)),
                ('flood_100yr_med_pct', models.FloatField(blank=True, null=True)),
                ('flood_100yr_high_pct', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='noah_flood', to='resilience.barangay')),
            ],
            options={
                'verbose_name_plural': 'NOAH Flood Hazards',
            },
        ),
        migrations.DeleteModel(
            name='BarangayClimateData',
        ),
        migrations.DeleteModel(
            name='BarangayHealthAccess',
        ),
        migrations.DeleteModel(
            name='BarangayInfrastructure',
        ),
        migrations.DeleteModel(
            name='DiseaseCase',
        ),
    ]
