# Generated by Django 5.2.7 on 2025-10-24 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience', '0005_remove_barangayhealthaccess_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resiliencescore',
            name='storm_surge_risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StormSurgeHazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssa1_low_pct', models.FloatField(blank=True, help_text='% of area in low surge zone', null=True)),
                ('ssa1_med_pct', models.FloatField(blank=True, null=True)),
                ('ssa1_high_pct', models.FloatField(blank=True, null=True)),
                ('ssa2_low_pct', models.FloatField(blank=True, null=True)),
                ('ssa2_med_pct', models.FloatField(blank=True, null=True)),
                ('ssa2_high_pct', models.FloatField(blank=True, null=True)),
                ('ssa3_low_pct', models.FloatField(blank=True, null=True)),
                ('ssa3_med_pct', models.FloatField(blank=True, null=True)),
                ('ssa3_high_pct', models.FloatField(blank=True, null=True)),
                ('ssa4_low_pct', models.FloatField(blank=True, null=True)),
                ('ssa4_med_pct', models.FloatField(blank=True, null=True)),
                ('ssa4_high_pct', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storm_surge', to='resilience.barangay')),
            ],
            options={
                'verbose_name_plural': 'Storm Surge Hazards',
            },
        ),
    ]
