# Generated by Django 5.2.7 on 2025-10-24 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience', '0006_resiliencescore_storm_surge_risk_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resiliencescore',
            name='liquefaction_risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LiquefactionHazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_pct', models.FloatField(blank=True, help_text='% of area with low susceptibility', null=True)),
                ('med_pct', models.FloatField(blank=True, null=True)),
                ('high_pct', models.FloatField(blank=True, null=True)),
                ('very_high_pct', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquefaction', to='resilience.barangay')),
            ],
            options={
                'verbose_name_plural': 'Liquefaction Hazards',
            },
        ),
    ]
