# Generated by Django 5.2.7 on 2025-10-29 09:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience', '0007_resiliencescore_liquefaction_risk_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TropicalCycloneTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('begin_index', models.IntegerField(help_text='Start index')),
                ('end_index', models.IntegerField(help_text='End index')),
                ('track', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('year', models.IntegerField(default=2024)),
                ('affected_negros', models.BooleanField(default=False, help_text='Did this cyclone affect Negros Oriental?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tropical Cyclone Tracks',
                'ordering': ['name'],
            },
        ),
    ]
