# Generated by Django 5.2.7 on 2025-10-29 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience', '0008_tropicalcyclonetrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('avg_aqi', models.FloatField(help_text='Average AQI for the month')),
                ('avg_pm25', models.FloatField(blank=True, help_text='PM2.5 average', null=True)),
                ('avg_pm10', models.FloatField(blank=True, help_text='PM10 average', null=True)),
                ('avg_o3', models.FloatField(blank=True, help_text='Ozone average', null=True)),
                ('avg_no2', models.FloatField(blank=True, help_text='NO2 average', null=True)),
                ('avg_co', models.FloatField(blank=True, help_text='CO average', null=True)),
                ('data_points', models.IntegerField(default=0, help_text='Number of hourly readings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_quality', to='resilience.municipality')),
            ],
            options={
                'verbose_name_plural': 'Air Quality Data',
                'ordering': ['-year', '-month', 'municipality'],
                'unique_together': {('municipality', 'year', 'month')},
            },
        ),
    ]
