# Generated by Django 5.2.7 on 2025-10-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience', '0009_airqualitydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='resiliencescore',
            name='air_quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
