# Generated by Django 5.2.7 on 2025-10-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilience', '0010_resiliencescore_air_quality_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='climate_summary',
            field=models.TextField(blank=True, help_text='Summary of climate projections (2036-2099)', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='rainfall_trend',
            field=models.CharField(blank=True, help_text='Increase/Decrease/Stable', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='temperature_trend',
            field=models.CharField(blank=True, help_text='Increase/Decrease/Stable', max_length=50, null=True),
        ),
    ]
